runtime: python39

entrypoint: gunicorn -b :$PORT main:app --timeout 120


handlers:
  - url: /static
    static_dir: static

 

env_variables:
  FLASK_ENV: production  
  GAE_USE_SOCKETS_HTTPLIB : 'true'
